// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PUConstruir.Data;

#nullable disable

namespace PUConstruir.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20240613161908_Criacao Banco Teste")]
    partial class CriacaoBancoTeste
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaterialModelProjetoModel", b =>
                {
                    b.Property<int>("MateriaisId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetosId")
                        .HasColumnType("int");

                    b.HasKey("MateriaisId", "ProjetosId");

                    b.HasIndex("ProjetosId");

                    b.ToTable("ProjetoMateriais", (string)null);
                });

            modelBuilder.Entity("OrcamentoModelProjetoModel", b =>
                {
                    b.Property<int>("OrcamentosId")
                        .HasColumnType("int");

                    b.Property<int>("ProjetosId")
                        .HasColumnType("int");

                    b.HasKey("OrcamentosId", "ProjetosId");

                    b.HasIndex("ProjetosId");

                    b.ToTable("OrcamentoProjetos", (string)null);
                });

            modelBuilder.Entity("PUConstruir.Models.MaterialModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Comprimento")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Largura")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Peso")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Um")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPadrao")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("PUConstruir.Models.OrcamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("PUConstruir.Models.ProjetoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicial")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeProjeto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("PUConstruir.Models.ServicoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPadrao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Servicos");
                });

            modelBuilder.Entity("PUConstruir.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjetoModelServicoModel", b =>
                {
                    b.Property<int>("ProjetosId")
                        .HasColumnType("int");

                    b.Property<int>("ServicosId")
                        .HasColumnType("int");

                    b.HasKey("ProjetosId", "ServicosId");

                    b.HasIndex("ServicosId");

                    b.ToTable("ProjetoServicos", (string)null);
                });

            modelBuilder.Entity("MaterialModelProjetoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.MaterialModel", null)
                        .WithMany()
                        .HasForeignKey("MateriaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUConstruir.Models.ProjetoModel", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrcamentoModelProjetoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.OrcamentoModel", null)
                        .WithMany()
                        .HasForeignKey("OrcamentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUConstruir.Models.ProjetoModel", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PUConstruir.Models.MaterialModel", b =>
                {
                    b.HasOne("PUConstruir.Models.UsuarioModel", "Usuario")
                        .WithMany("Materiais")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PUConstruir.Models.OrcamentoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.UsuarioModel", "Usuario")
                        .WithMany("Orcamentos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PUConstruir.Models.ProjetoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.UsuarioModel", "Usuario")
                        .WithMany("Projetos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PUConstruir.Models.ServicoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.UsuarioModel", "Usuario")
                        .WithMany("Servicos")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjetoModelServicoModel", b =>
                {
                    b.HasOne("PUConstruir.Models.ProjetoModel", null)
                        .WithMany()
                        .HasForeignKey("ProjetosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PUConstruir.Models.ServicoModel", null)
                        .WithMany()
                        .HasForeignKey("ServicosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PUConstruir.Models.UsuarioModel", b =>
                {
                    b.Navigation("Materiais");

                    b.Navigation("Orcamentos");

                    b.Navigation("Projetos");

                    b.Navigation("Servicos");
                });
#pragma warning restore 612, 618
        }
    }
}
